[package]
name = "github_follow_unfollow"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking"] }
serde_json = "1.0.130"
serde = { version = "1.0.204", features = ["derive"] }
dotenv = "0.15.0"